### ISSUE TITLE
Im facing a challenge to deploy on heroku...

### ISSUE THREAD

**Issue by brunoalfred** [strapi/strapi-starter-next-ecommerce#13] opened 2021-04-20 09:58 UTC
<img width="1059" alt="Screenshot 2021-04-20 at 12 53 25" src="https://user-images.githubusercontent.com/55545250/115377088-f4152880-a1d7-11eb-8716-77dd98c77956.png">

**Comment by brunoalfred** [comment] 2021-04-20 09:59
I think there is a problem with port assignment from heroku, 

as it is show on the error entry :

```
2021-04-20T09:49:07.905353+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

**Comment by remidej** [comment] 2021-04-20 13:18
Hello Bruno,

It looks like the problem is not coming from this starter, so we won't fix this here. Instead you can:

- Check out our [Heroku docs](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/heroku.html#heroku)
- Get community support on the [Strapi forum](https://forum.strapi.io/tag/deploy)

**Closed as completed by remidej** 2021-04-20 13:18 UTC

**Comment by brunoalfred** [comment] 2021-04-24 13:55
<img width="1280" alt="Screenshot 2021-04-24 at 17 11 47" src="https://user-images.githubusercontent.com/55545250/115961721-4def5880-a520-11eb-8f3a-15204b65e6ba.png">
<img width="1036" alt="Screenshot 2021-04-24 at 17 12 21" src="https://user-images.githubusercontent.com/55545250/115961728-53e53980-a520-11eb-9597-8096d40f5cce.png">



Help @remidej, please... if you have any idea??
The issues are: 

1. What is wrong with the images being loaded from the server???

**Comment by remidej** [comment] 2021-04-26 15:35
You'll need to set up an external file upload provider for Heroku. See this section of the docs: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/heroku.html#file-uploads
